import requests
import base64
import json
import logging
from datetime import datetime

# Set up logging
logging.basicConfig(filename="skl_gen.log", level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")

# Function to read the chosen prompt from a file
def read_chosen_prompt():
    with open("chosen_prompt.txt", "r") as f:
        return f.read().strip()


# Read image file from disk
with open("D:\\sentiMation\\generators\\sketch2life\\assets\\cn_skl.png", "rb") as image_file:
    encoded_image = base64.b64encode(image_file.read()).decode('utf-8')

# Define the API URL
api_url = "http://127.0.0.1:7860/sdapi/v1/img2img"

# Define the payload for animate_diff_args
animate_diff_args = {
    "model": "mm_sd_v15_v2.ckpt",
    "format": ["MP4", "PNG"],
    "enable": True,
    "video_length": 300,
    "fps": 30,
    "loop_number": 0,
    "closed_loop": "A",
    "batch_size": 7,
    "stride": 1,
    "overlap": -1,
    "interp": "NO",
    "interp_x": 10,
    "latent_power": 1,               # Latent power 
    "last_frame": [encoded_image],     # Optional last frame
    "latent_power_last": 1 # Optional latent power for last frame
}

# Read the prompt from the file generated by the first script
chosen_prompt = read_chosen_prompt()

# Define the JSON payload
json_payload = {
    "init_images": [encoded_image],
    "prompt": chosen_prompt,
    "negative_prompt": "Compression artifacts, nudity, nsfw, Bad art, worst quality, low quality, plastic, fake, bad limbs, conjoined, featureless, bad features, incorrect objects, watermark, piercings, logo, watermark, blurry, grainy",
    "batch_size": 1,
    "sampler_name": "DDIM",
    "steps": 12,
    "cfg_scale": 7,
    "denoising_strength": 0.7,
    "save_images": True,
    "width": 512,
    "height": 690,
    "alwayson_scripts": {
        "AnimateDiff": {"args": [animate_diff_args]}
    }
}

# Define headers
headers = {
    "Content-Type": "application/json"
}

# Call the API
response = requests.post(api_url, headers=headers, json=json_payload)

# Check for successful response
if response.status_code == 200:
    r = response.json()
    # Assuming 'images' key contains a list of base64 encoded strings
    if 'images' in r and r['images']:
        base64_data = r['images'][0]
        
        # Decode base64 (assuming the data is direct base64 of MP4, no additional splitting needed)
        mp4_data = base64.b64decode(base64_data)

        # Write the MP4 data to a file
        with open('lowscale.mp4', 'wb') as file:
            file.write(mp4_data)
        print("MP4 file saved as 'lowscale.mp4'.")
    else:
        print("No image data found in the response.")
else:
    print(f"API call failed. Status Code: {response.status_code}, Response: {response.text}")


# Debugging and Logging
if response.status_code == 200:
    logging.info(f"API call successful. Status Code: {response.status_code}")
    response_json = response.json()

    # Write JSON response to a file
    with open("api_response.txt", "w") as file:
        json.dump(response_json, file, indent=4)

else:
    logging.error(f"API call failed. Status Code: {response.status_code}, Response: {response.text}")
    response_json = {}

