import requests
import base64
import json
import logging
from datetime import datetime

# Set up logging
logging.basicConfig(filename="hypnotic_log.log", level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")

# Function to read the chosen prompt from a file
def read_chosen_prompt():
    with open("chosen_prompt.txt", "r") as f:
        chosen_prompt = f.read().strip()
        logging.info(f"Chosen prompt: {chosen_prompt}")
        return chosen_prompt

# Define the API URL
api_url = "http://127.0.0.1:7860/sdapi/v1/txt2img"

# Define the payload for animate_diff_args
animate_diff_args = {
    "model": "animatediffMotion_v15V2.ckpt",
    "format": ['MP4'],
    "enable": True,
    "video_length": 40,
    "fps": 20,
    "loop_number": 0,
    "closed_loop": "R+P",
    "batch_size": 8,
    "stride": 1,
    "overlap": -1,
    "interp": "NO",
    "interp_x": 10
}

# Read the prompt from the file generated by the first script
chosen_prompt = read_chosen_prompt()

# Define the JSON payload
json_payload = {
    "prompt": chosen_prompt,
    "negative_prompt": "Compression artifacts, nudity, nsfw, Bad art, worst quality, low quality, plastic, fake, bad limbs, conjoined, featureless, bad features, incorrect objects, watermark, piercings, logo, watermark, blurry, grainy",
    "batch_size": 1,
    "sampler_name": "Euler a",
    "steps": 30,
    "cfg_scale": 10,
    "width": 512,
    "height": 512,
    "alwayson_scripts": {
        "AnimateDiff": {"args": [animate_diff_args]}
    }
}

# Define headers
headers = {
    "Content-Type": "application/json"
}

# Call the API
response = requests.post(api_url, headers=headers, json=json_payload)

# Debugging and Logging
if response.status_code == 200:
    logging.info(f"API call successful. Status Code: {response.status_code}")
else:
    logging.error(f"API call failed. Status Code: {response.status_code}, Response: {response.text}")

# Parse the JSON response
response_json = response.json()
